### ISSUE TITLE
FATAL Error while trying to import via Coinbase REST API

### ISSUE THREAD

**Issue by jameskupke** [eprbell/dali-rp2#10]
Tried to import via Coinbase API, it processes for a minute or two and then errors out. Nothing created in output folder.

Version:
DaLI 0.3.20 (https://pypi.org/project/dali_rp2/)
OS: Fedora

Ini file:

[dali.plugin.input.rest.coinbase]
account_holder = my name 
api_key = ***
api_secret = ***

Logs:

2022-03-23 22:30:43,532/dali/INFO: Reading crypto data using plugin 'dali.plugin.input.rest.coinbase'
2022-03-23 22:34:30,411/dali/INFO: Resolving transactions
2022-03-23 22:34:30,411/dali/ERROR: Fatal exception occurred:
Traceback (most recent call last):
  File "/home/james/.local/lib/python3.10/site-packages/dali/dali_main.py", line 107, in input_loader
    resolved_transactions: List[AbstractTransaction] = resolve_transactions(transactions, dali_configuration, args.read_spot_price_from_web)
  File "/home/james/.local/lib/python3.10/site-packages/dali/transaction_resolver.py", line 169, in resolve_transactions
    transaction = _apply_transaction_hint(transaction_list[0], global_configuration)
  File "/home/james/.local/lib/python3.10/site-packages/dali/transaction_resolver.py", line 211, in _apply_transaction_hint
    if transaction.unique_id not in global_configuration[Keyword.TRANSACTION_HINTS.value]:
KeyError: 'transaction_hints'
2022-03-23 22:34:30,412/dali/INFO: Log file: ./log/rp2_2022_03_23_22_30_43_325160.log
2022-03-23 22:34:30,412/dali/INFO: Generated output directory: output/
2022-03-23 22:34:30,412/dali/INFO: Done

**Comment by jameskupke** [comment]
Also, not sure if these are all  needed, but here is the API permissions given for my key:
address
email
offline
access
openid
phone
profile
wallet:accounts:read
wallet:addresses:read
wallet:buys:read
wallet:checkouts:read
wallet:contacts:read
wallet:deposits:read
wallet:notifications:read
wallet:orders:read
wallet:payment-methods:read
wallet:sells:read
wallet:supported-assets:read
wallet:trades:read
wallet:transactions:read
wallet:user:email
wallet:user:read
wallet:withdrawals:read

**Comment by eprbell** [comment]
Thanks for reporting a bug! I just fixed it: can you update DaLI to version 0.3.21 and try again?

**Comment by jameskupke** [comment]
Yep, trying now actually.

**Comment by jameskupke** [comment]
I see the ods and config file now. Will test it on RP2, closing this issue as it looks fixed.
