### ISSUE TITLE
Error using coinbase plugin: "TypeError: 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by kiates** [eprbell/dali-rp2#131]
Trying out your amazing project.  I was able to import Coinbase Pro data so far, but moving to Coinbase I get this error. 

> INFO: Reading crypto data using plugin 'dali.plugin.input.rest.coinbase'
ERROR: Fatal exception occurred:
Traceback (most recent call last):
  File "C:\Users\cyates\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dali\dali_main.py", line 164, in _dali_main_internal
    result_list = pool.map(_input_plugin_helper, input_plugin_args_list)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Users\cyates\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dali\dali_main.py", line 202, in _input_plugin_helper
    plugin_transactions = input_plugin.load(country)
  File "C:\Users\cyates\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dali\plugin\input\rest\coinbase.py", line 186, in load
    process_account_result_list = pool.map(self._process_account, self.__get_accounts())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Users\cyates\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dali\plugin\input\rest\coinbase.py", line 465, in _process_account
    self._process_transfer(transaction, currency, in_transaction_list, out_transaction_list, intra_transaction_list)
  File "C:\Users\cyates\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dali\plugin\input\rest\coinbase.py", line 566, in _process_transfer
    and transaction[_TO][_RESOURCE] == _USER
TypeError: 'NoneType' object is not subscriptable
INFO: Log file: ./log/rp2_2023_04_01_11_21_43_734907.log
INFO: Generated output directory: dali-output
INFO: Done

**Comment by kiates** [comment]
Doing a little logging, it looks like part of the transaction data is not expected to be empy/None:
![image](https://user-images.githubusercontent.com/1494951/229310249-f804b882-cc37-4fd2-97f1-fdc66d5e096e.png)

Left is another transaction just before the error one, and right is the one that triggers the error.

**Comment by kiates** [comment]
Adding these two lines to try and fix the issue to at least make it not die:
![image](https://user-images.githubusercontent.com/1494951/229310518-9965d639-d410-4ef4-a8de-dec745342f89.png)

I'm assuming that the data is correct coming from the Coinbase API and the plugin has just not experienced the pattern before.

For reference here is what is generated in the ods output:
![image](https://user-images.githubusercontent.com/1494951/229310714-191e363a-ec2a-4d5a-ae6e-8883c4d0d9d0.png)

**Comment by kiates** [comment]
If this looks like the right approach, I can open a PR. Actually I'll just open one for discussion either way.

**Comment by eprbell** [comment]
Thanks for reporting a bug! What version of DaLI and RP2 are you using? Can you do the following:
* `rm -rf log/`
* edit your .ini file and make sure the Coinbase section has `thread_count = 1`
* rerun DaLI with debug logging: `LOG_LEVEL=DEBUG bin/dali_us -t 1 <rest of your parameters>`
* open the log that has just been generated in `log/` and go to the bottom
* look for the last line that begins with: `<date>/Coinbase/<user>/DEBUG:` and paste it here (feel free to remove personal information)

**Comment by eprbell** [comment]
> If this looks like the right approach, I can open a PR. Actually I'll just open one for discussion either way.

Good idea.

**Comment by kiates** [comment]
Here is what the output looks like for the 2.833888 transaction above:
![image](https://user-images.githubusercontent.com/1494951/229311350-1789b5a7-3e9e-46ff-87e4-d25a7132bfe1.png)
