### ISSUE TITLE
Dev Environment

### ISSUE THREAD

**Issue by stevendavis** [eprbell/dali-rp2#30]
Having a couple issues with black.

1. The newest version of black is behaving differently from older versions.  It removes the excess parenthesis here:

```

$ black --version
black, 22.3.0 (compiled: yes)

                raise RP2ValueError(
                    (
                        f"Invalid converstion {Keyword.INTRA.value}->{Keyword.OUT.value}: "
                        f"{Keyword.CRYPTO_OUT_NO_FEE.value}/{Keyword.CRYPTO_FEE.value} canot be unknown: {transaction}"
                    )
                )

```

2. There is a compatibility problem with black, click, and pre-commit.  Black runs fine by itself from the command line, but pre-commit keeps a separate copy of black and click, and they are not compatible anymore.  I think this could be fixed by upgrading the black version inside the pre-commit package cache.  However, we will need to re-run black on the entire source tree and commit the resulting changes since the latest version appears to behave a bit differently.

```
$ black --version
black, 22.3.0 (compiled: yes)

$ black  src/dali/transaction_resolver.py
All done! ✨ 🍰 ✨
1 file left unchanged.

$ pre-commit run --files src/dali/transaction_resolver.py
Check python ast.........................................................Passed
fix UTF-8 byte order marker..............................................Passed
Check builtin type constructor use.......................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...........................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check Toml...........................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Detect Destroyed Symlinks................................................Passed
Detect Private Key.......................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Pretty format JSON...................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
flake8...................................................................Passed
isort....................................................................Passed
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "C:\Users\me\.conda\envs\dali-rp2\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\me\.conda\envs\dali-rp2\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\.cache\pre-commit\repoq4eabbla\py_env-default\Scripts\black.EXE\__main__.py", line 7, in <module>
  File "C:\Users\me\.cache\pre-commit\repoq4eabbla\py_env-default\lib\site-packages\black\__init__.py", line 1282, in patched_main
    patch_click()
  File "C:\Users\me\.cache\pre-commit\repoq4eabbla\py_env-default\lib\site-packages\black\__init__.py", line 1268, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (C:\Users\me\.cache\pre-commit\repoq4eabbla\py_env-default\lib\site-packages\click\__init__.py)

pyupgrade................................................................Passed
blacken-docs.............................................................Passed



```

**Comment by eprbell** [comment]
Interesting... looks like this is a black bug that they fixed in version 22.3.0: https://github.com/psf/black/issues/2964

I'm OK with updating black to latest version and preprocessing the entire source (hopefully it's not a huge diff), however let's do that in a separate PR (I mean separate from the other work you're doing on cache). 

I think you'll have to update the black version in .pre-commit-config.yaml (both under "black" and "blacken-docs").

**Comment by eprbell** [comment]
Actually I ended up fixing it: just pull the latest code. Thanks for reporting it.

**Comment by stevendavis** [comment]
Thanks for the prompt fix.  I'm getting further, black runs without errors, but now blacken-docs is failing.  I don't mean to be a pest, I'm just trying to make easier for new developers to join the team.

```
$ pre-commit run --file src/dali/transaction_resolver.py
Check python ast.........................................................Passed
fix UTF-8 byte order marker..............................................Passed
Check builtin type constructor use.......................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...........................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check Toml...........................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Detect Destroyed Symlinks................................................Passed
Detect Private Key.......................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Pretty format JSON...................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
flake8...................................................................Passed
isort....................................................................Passed
black....................................................................Passed
pyupgrade................................................................Passed
blacken-docs.............................................................Failed
- hook id: blacken-docs
- exit code: 1

Traceback (most recent call last):
  File "C:\Users\me\.conda\envs\dali-rp2\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\me\.conda\envs\dali-rp2\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\.cache\pre-commit\repok68fano3\py_env-python3\Scripts\blacken-docs.EXE\__main__.py", line 7, in <module>
  File "C:\Users\me\.cache\pre-commit\repok68fano3\py_env-python3\lib\site-packages\blacken_docs.py", line 235, in main
    black_mode = black.FileMode(
  File "<string>", line 3, in __init__
TypeError: set object expected; got list
```

**Comment by eprbell** [comment]
No, it's all good: if it doesn't work, it doesn't work and it's great that you open issues. This one is a bit strange because it's not happening on Github, but I did see it on my local machine... I reverted the black version to 20.8b1 in the blacken-docs section only. Can you git pull and try again?

**Comment by stevendavis** [comment]
Working now, thank you.  Closing this issue.

**Comment by stevendavis** [comment]
The developer docs should probably mention you must run this command as part of setting up your environment:
`
    pre-commit install
`

**Comment by eprbell** [comment]
These are the instructions for development setup: https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#setup

There is no need to run `pre-commit install`
